application: he3-lib
version: rel001
runtime: python
api_version: 1

handlers:

- url: /test.*
  login: admin  # This is important if you deploy the test directory in production!
  script: gaeunit.py
